//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vod
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Banner()
        {
            this.Bundles = new HashSet<Bundle>();
        }
    
        public int Id { get; set; }
        public string Url { get; set; }
        public int Width { get; set; }
        public int Height { get; set; }
        public string UrlToClick { get; set; }
        public Nullable<int> MovieId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> GenreId { get; set; }
        public string ListName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bundle> Bundles { get; set; }
    }
}
