//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vod
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Movie()
        {
            this.Qualities = "";
            this.Downloadables = "";
            this.Teaser = "";
            this.FolderName = "";
            this.Bundles = new HashSet<Bundle>();
            this.Categories = new HashSet<Category>();
            this.Genres = new HashSet<Genre>();
            this.Roles = new HashSet<Role>();
            this.Comments = new HashSet<Comment>();
            this.Rates = new HashSet<Rate>();
            this.Purchases = new HashSet<Purchase>();
            this.PanelUsers = new HashSet<PanelUser>();
            this.Childs = new HashSet<Movie>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public long Duration { get; set; }
        public double Rate { get; set; }
        public int RatedUsers { get; set; }
        public int CommentId { get; set; }
        public int Visit { get; set; }
        public int Year { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int ThumbUps { get; set; }
        public int ThumbDowns { get; set; }
        public bool Featured { get; set; }
        public int Price { get; set; }
        public string Qualities { get; set; }
        public string Downloadables { get; set; }
        public string Teaser { get; set; }
        public string FolderName { get; set; }
        public bool Disable { get; set; }
        public double EditorialRate { get; set; }
        public bool Filter { get; set; }
    
        public virtual Image Thumbnail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bundle> Bundles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Category> Categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Genre> Genres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Role> Roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rate> Rates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchase> Purchases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PanelUser> PanelUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Movie> Childs { get; set; }
        public virtual Movie Parent { get; set; }
    }
}
