//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vod
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VodioContainer : DbContext
    {
        public VodioContainer()
            : base("name=VodioContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Movie> Movies { get; set; }
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<Home> Homes { get; set; }
        public virtual DbSet<Bundle> Bundles { get; set; }
        public virtual DbSet<Banner> Banners { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Genre> Genres { get; set; }
        public virtual DbSet<Agent> Agents { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<Rate> Rates { get; set; }
        public virtual DbSet<CategoryGenre> CategoryGenres { get; set; }
        public virtual DbSet<Purchase> Purchases { get; set; }
        public virtual DbSet<Factor> Factors { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<PanelUser> PanelUsers { get; set; }
        public virtual DbSet<Email> Emails { get; set; }
    }
}
